SET AUTOCOMMIT OFF 

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

INSERT INTO CUENTA (ID, SALDO, TIPO, ESTADO, FECHACREACION)
VALUES (1, 0, 'ahorros', 'Activo', TO_DATE('20/04/24', 'DD/MM/YY'));

UPDATE CUENTA
SET SALDO = SALDO + 1000000
WHERE ID = 1;

INSERT INTO LOGOPERACIONES (ID, CUENTA_ID, TIPO_OPERACION, MONTO, FECHA, DESCRIPCION)
VALUES (1, 1, 'Consignación', 1000000, TO_DATE('20/04/24', 'DD/MM/YY'), 'Consignación de 1 millón de pesos');

UPDATE CUENTA
SET SALDO = SALDO - 50000
WHERE ID = 2;

INSERT INTO LOGOPERACIONES (ID, CUENTA_ID, TIPO_OPERACION, MONTO, FECHA, DESCRIPCION)
VALUES (2, 2, 'Retiro', 50000, CURRENT_DATE, 'Retiro de 50,000 pesos');

COMMIT;

SELECT ID, SALDO FROM CUENTA
WHERE ID = 1 OR ID =2;