SET AUTOCOMMIT OFF 

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

UPDATE CUENTA
SET SALDO = SALDO - 30000
WHERE ID = 1;

INSERT INTO LOGOPERACIONES (ID, CUENTA_ID, TIPO_OPERACION, MONTO, FECHA, DESCRIPCION)
VALUES (3, 1, 'Retiro', 30000, TO_DATE('20/04/24', 'DD/MM/YY'), 'Retiro de 30 mil de pesos');

UPDATE CUENTA
SET SALDO = SALDO + 5000
WHERE ID = 2;

INSERT INTO LOGOPERACIONES (ID, CUENTA_ID, TIPO_OPERACION, MONTO, FECHA, DESCRIPCION)
VALUES (4, 2, 'Intereses', 5000, TO_DATE('20/04/24', 'DD/MM/YY'), 'Suma de intereses de 5 mil de pesos');

COMMIT;

SELECT ID, SALDO FROM CUENTA
WHERE ID = 1 OR ID =2;